default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: janm
  password: <%= Rails.application.credentials.db[:password] %>
  host: localhost
production:
  <<: *default
  database: aliexpress_development

development:
  <<: *default
  database: aliexpress_development

test:
  <<: *default
  database: aliexpress_test
