# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d56aa3522b7cd8a19efae303020c226e7eceb41073e389df8ff6bb7694a50487ba585fb869bf655cb1b4dc48bb20f11e58aea39c82ee1bb62c201e8008b425

test:
  secret_key_base: 3adc7a90abc4c2e8825fd075b952b4b491f2c23c93d6e8fdb05b03b21ae649d2c81a4a5fb25bfb626aa2c461f72a17a30095d56a8f6cb2d4560e6e97a16988ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
